name: Build and Push Image

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ai-agent

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::557514745876:role/github-actions-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        run: |
          IMAGE=557514745876.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${GITHUB_SHA}
          docker build -t $IMAGE .
          docker push $IMAGE
